language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
matrix:
  exclude:
    - python: 3.3
      env: DJANGO="Django>=1.9,<1.10"
    - python: 3.3
      env: DJANGO="Django>=1.10,<1.11"
    - python: 3.4
      env: DJANGO="Django>=1.6,<1.7"
    - python: 3.5
      env: DJANGO="Django>=1.5,<1.6"
    - python: 3.5
      env: DJANGO="Django>=1.6,<1.7"
    - python: 3.5
      env: DJANGO="Django>=1.7,<1.8"
install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements-travisci.txt
script:
  - python runtests.py
